apiVersion: v1
kind: Secret
metadata:
  name: nginx-registry-fit2cloud-com-key
  #namespace: jenkins
data:
    .dockerconfigjson: ewoJICAgICJhdXRocyI6IHsKICAgICAgICAgICAgInJlZ2lzdHJ5Lmt1YmVhcHBzLmZpdDJjbG91ZC5jb20iOiB7CgkJCSAgICAiYXV0aCI6ICJZV1J0YVc0NllXUnRhVzR4TWpNPSIKCQkgICAgICAgIH0KCSAgICAgICAgfSwKCSAgICAiSHR0cEhlYWRlcnMiOiB7CgkJICAgICJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTguMDkuOSAobGludXgpIgoJICAgIH0KICAgIH0K
type: kubernetes.io/dockerconfigjson
